### PR TITLE
WebP support

### PR DESCRIPTION
**Pull request by powernic**
This PR Adds WebP source support

It's works for this html;
```
<picture>
  <source type="image/webp" srcset="1.jpg.webp">
  <img src="1.jpg" >
</picture>
```

### CODE REVIEW

**Comment by noeldelgado** [comment]
Hi @powernic,

First of all thanks for interest in contributing to this project. Thanks to you I just learned about the existence of the read-only `currentSrc` property. 🤓 

Now that I see your intent here, it really got me thinking about how this project lacks support for the `<picture>` element. It was created 6 years ago as a result of an small experiment and I haven't paid too much attention to it since then (it was updated this year, but just add distribution to the NPM registry).

Ok, after thinking about this for a bit, I can see another scenario where it will still not work. Please see the example below:
```html
<picture>
  <source media="(max-width: 459px)" srcset="400.webp 1x, 800.webp 2x" type="image/webp">
  <source media="(max-width: 676px)" srcset="308.webp 1x, 616.webp 2x" type="image/webp">
  <source media="(max-width: 893px)" srcset="272.webp 1x, 544.webp 2x" type="image/webp">
  <source media="(min-width: 894px)" srcset="227.webp 1x, 454.webp 2x" type="image/webp">

  <source media="(max-width: 459px)" srcset="400.png 1x, 800.png 2x" type="image/png">
  <source media="(max-width: 676px)" srcset="308.png 1x, 616.png 2x" type="image/png">
  <source media="(max-width: 893px)" srcset="272.png 1x, 544.png 2x" type="image/png">
  <source media="(min-width: 894px)" srcset="227.png 1x, 454.png 2x" type="image/png">

  <img src="400.png" width="400" height="225" alt="">
</picture>
```

In this case, I think it will be expected that any `png` or `webp` source gets replaced with its corresponding pixelated version, including the additional set of images separated by a comma, right?

To start approaching into this, I created the following demo:
https://codepen.io/noeldelgado/pen/3fd4255074860498a030fbd8b91db50f?editors=1010

There I am overriding the `replace` and `_getDataURL` methods of the library to iterate over the sources and replace its `srcset` (taking into account the possibility of multiple images separated by comma). This is not ideal though as the same canvas data is used to generate the data URL for every one of the them and, in fact, those other images could be different depending on the use case (responsiveness, art-direction, etc).

So, maybe, just an initial idea, this could be implemented like: (?)
- let the constructor allow image or picture elements
- if image then do what it is already doing (no changes here)
- if picture then iterate over its sources and each set of images
    - generate a new canvas data for every image on the set
    - replace each image with its corresponding data URL

Well, just my initial thoughts on this. What do you think?

**Comment by powernic** [comment]
You're almost right. Except for the last clause. Picture renders only one image, so only it needs to be changed. When the window is changed, the new currentSrc needs to be replaced.
```
Pixelify.prototype.replace = function() {
  const parent = this.image.parentElement;
  
  if (parent.constructor.name === 'HTMLPictureElement') {
    const sources = Array.from(parent.querySelectorAll('source'));
    const currentSrc = this.image.currentSrc;
    for (let i = 0, len = sources.length; i < len; i++) 
      sources[i].srcset = sources[i].srcset
        .split(',')
        .map(str => str.replace(currentSrc, this._getDataURL(sources[i].type)))
        .toString();
  } 
  
  this.image.setAttribute('src', this._getDataURL());
  
  return this; 
}
```

**Comment by powernic** [comment]
@noeldelgado 
You're almost right. Except for the last clause. Picture renders only one image, so only it needs to be changed. The new currentSrc needs to be replaced when the window is changed.
```
Pixelify.prototype.replace = function() {
  const parent = this.image.parentElement;
  
  if (parent.constructor.name === 'HTMLPictureElement') {
    const sources = Array.from(parent.querySelectorAll('source'));
    const currentSrc = this.image.currentSrc;
    for (let i = 0, len = sources.length; i < len; i++) 
      sources[i].srcset = sources[i].srcset
        .split(',')
        .map(str => str.replace(currentSrc, this._getDataURL(sources[i].type)))
        .toString();
  }  
  
  return this; 
}
```

**Comment by noeldelgado** [comment]
@powernic 
Awesome, good stuff, that looks better.

I’ll be taking a couple of days off (with no computer).
I’ll be able look into this further when I get back.

Thanks for your insights 🔍

**Comment by noeldelgado** [comment]
Hi @powernic,
would you mind trying this version to see if this works for you?: https://github.com/noeldelgado/pixelify-img/blob/feature/ps/src/pixelify.js

For the following scenario:
```html
<picture>
  <source type="image/webp" srcset="1.jpg.webp">
  <img src="1.jpg" >
</picture>
```
You should now pass the picture reference instead of the one to the img:
```js
new Pixelify( document.querySelector('picture')  )
```
It should be able to handle `webp` or whatever that is on the `srcset`.

You can find 2 more html examples I have tried so far here: https://github.com/noeldelgado/pixelify-img/pull/4

The thing now listens to the window resize event (as advised) to replace the currentSrc in case it hasn't been replaced already.

**Comment by powernic** [comment]
@noeldelgado Hi, it works great for picture,  but stopped working for a regular img! 
`  `

**Comment by noeldelgado** [comment]
Wow, interesting @powernic, thanks for that!

I was able to replicate it, though it's inconsistent.

Are you getting a totally transparent image as a result or another type of error?

**Comment by powernic** [comment]
@noeldelgado just nothing happens to the img

**Comment by noeldelgado** [comment]
@powernic could you share the source somewhere for me to replicate the error? I have tried with `.jpg` and it is working for me :/

**Comment by powernic** [comment]
@noeldelgado  Sorry, it works fine!

**Pull request closed without merging**
